const projects = [
  {
    name: "Flow canvas",
    description:
      "A new kind of static site generator that combines the best parts of modern build tools.",
    slug: "chatbots",
    id: "chatbots",
    tech: [
      "TypeScript",
      "React",
      "Node.js",
      "PostgreSQL",
      "Redux Tollkit",
      "Redux-Saga",
      "SASS",
      "Cypress",
      "Jsplumb",
      "Docker",
      "Jenkins",
    ],
    image: "/flow.png",
  },
  {
    name: "Webchat",
    description: "some webchat description",
    slug: "webchat",
    id: "webchat",
    tech: [
      "TypeScript",
      "React",
      "Zustand",
      "SASS",
      "Cypress",
      "React-Query",
      "Vaniila JS",
      "Jenkins",
    ],
    image: "/webchat.png",
  },
  {
    name: "Sharable shopping List",
    description: "some webchat description",
    slug: "shopping-list",
    id: "shopping-list",
    image: "/shopping-list.png",
    tech: [
      "Next.js",
      "TypeScript",
      "React",
      "Tailwind CSS",
      "Prisma",
      "Postgresql",
      "Google Auth",
      "Next Auth",
      "Docker",
      "Serverless",
      "Vercel",
    ],
  },
  {
    name: "Platform for creating AI chatbots and voicebots",
    description: "some webchat description",
    slug: "platform-chatbots",
    id: "platform-chatbots",
    tech: [
      "TypeScript",
      "React",
      "Node.js",
      "PostgreSQL",
      "Redux Tollkit",
      "Redux-Saga",
      "SASS",
      "Cypress",
      "Jsplumb",
      "Docker",
    ],
  },
  {
    name: "Internet and social media monitoring",
    description: "some webchat description",
    slug: "monitoring",
    id: "monitoring",
    tech: ["JavaScript", "React", "SASS", "Docker"],
  },
  {
    name: "Smart home app",
    description: "some webchat description",
    slug: "my-pi-home",
    image: "/my-pi-home.png",
    id: "my-pi-home",
    tech: [
      "NestJs",
      "Node.js",
      "React",
      "MongoDB",
      "Docker",
      "Rasberry Pi",
      "Python",
      "pm2",
    ],
  },
  {
    name: "Audio book reader for older people",
    description: "some webchat description",
    slug: "audio-book-reader",
    id: "audio-book-reader",
    tech: ["Python", "Rasberry Pi", "Node.js", "React", "Docker"],
  },
  // {
  //   name: "E-commerce shop",
  //   description: "some webchat description",
  //   slug: "shopping-list",
  //   id: "shopping-list",
  //   tech: ["JavaScript", "React", "SASS", "Docker"],
  // },
];

export { projects };
